=== ORCID/ORCID-Parent/schemas/orcid-client-group/1.0/orcid-client-group-1.0.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--
  
  =============================================================================
  Copyright (C) 2011-12 by ORCID
  
  Permission is hereby granted, free of charge, to any person obtaining a copy
  of this software and associated documentation files (the "Software"), to deal
  in the Software without restriction, including without limitation the rights
  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
  copies of the Software, and to permit persons to whom the Software is
  furnished to do so, subject to the following conditions:
  
  The above copyright notice and this permission notice shall be included in
  all copies or substantial portions of the Software.
  
  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
  THE SOFTWARE.
  =============================================================================
  
-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"
  targetNamespace="http://www.orcid.org/ns/orcid"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:orcid="http://www.orcid.org/ns/orcid">
  <xs:annotation>
    <xs:documentation> =============================================================================
      Copyright (C) 2011-12 by ORCID Permission is hereby granted, free of charge, to any person
      obtaining a copy of this software and associated documentation files (the "Software"), to deal
      in the Software without restriction, including without limitation the rights to use, copy,
      modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to
      permit persons to whom the Software is furnished to do so, subject to the following
      conditions: The above copyright notice and this permission notice shall be included in all
      copies or substantial portions of the Software. THE SOFTWARE IS PROVIDED "AS IS", WITHOUT
      WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
      MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
      AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN
      AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
      SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
      ============================================================================= 
    </xs:documentation>
    <xs:documentation>This schema describes the format used to define creation of groups of ORCID
      clients for OAuth2. The top level element is orcid-client-group.</xs:documentation>
  </xs:annotation>
  <xs:element name="orcid-client-group">
    <xs:annotation>
      <xs:documentation>A group of OAuth2 clients to be created, or have been created.</xs:documentation>
    </xs:annotation>
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="orcid:group-orcid" minOccurs="0"/>
        <xs:element ref="orcid:group-name"/>
        <xs:element ref="orcid:email"/>
        <xs:element ref="orcid:orcid-client" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="group-orcid" type="orcid:orcid">
    <xs:annotation>
      <xs:documentation>The overall ORCID identifier for the group of clients. If this is ommitted then a new group of clients will be created.</xs:documentation>
    </xs:annotation>
  </xs:element>
  <xs:element name="group-name" type="orcid:short-text">
    <xs:annotation>
      <xs:documentation>A decriptive name for the group of clients.</xs:documentation>
    </xs:annotation>
  </xs:element>
  <xs:element name="email" type="orcid:email">
    <xs:annotation>
      <xs:documentation>A contact email for the group of clients. This email will be contact in the event of any issues relating to the clients.</xs:documentation>
    </xs:annotation>
  </xs:element>
  <xs:element name="orcid-client">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="orcid:display-name"/>
        <xs:element ref="orcid:website"/>
        <xs:element ref="orcid:short-description"/>
        <xs:element ref="orcid:redirect-uris"/>
        <xs:element ref="orcid:client-id" minOccurs="0"/>
        <xs:element ref="orcid:client-secret" minOccurs="0"/>
      </xs:sequence>
      <xs:attribute name="type" type="orcid:client-type"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="display-name" type="orcid:short-text">
    <xs:annotation>
      <xs:documentation>The display name of the client. This will be shown to the user during OAuth2 authorization.</xs:documentation>
    </xs:annotation>
  </xs:element>
  <xs:element name="website" type="xs:anyURI">
    <xs:annotation>
      <xs:documentation>The address of the web user interface of the client system. The user will be
        able to navigate to this address during OAuth2 authorization, if they wish to do
        so.</xs:documentation>
    </xs:annotation>
  </xs:element>
  <xs:element name="short-description" type="orcid:short-text">
    <xs:annotation>
      <xs:documentation>A short description of the client system. This will be shown to the user
        during OAuth2 authorization.</xs:documentation>
    </xs:annotation>
  </xs:element>
  <xs:element name="redirect-uris">
    <xs:annotation>
      <xs:documentation>The list of redirect_uris that the client is permitted to use during OAuth2
        authorization.</xs:documentation>
    </xs:annotation>
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="orcid:redirect-uri"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="redirect-uri" type="xs:anyURI"/>
  <xs:element name="client-id" type="orcid:orcid">
    <xs:annotation>
      <xs:documentation>The client ID to be used by the client for OAuth2 authorization. If this is absent then a new client will be created.</xs:documentation>
    </xs:annotation>
  </xs:element>
  <xs:element name="client-secret" type="orcid:short-text">
    <xs:annotation>
      <xs:documentation>The client secret to be used by the client for OAuth2 authorization. This
        will be generated by ORCID and returned to the administrators of the client system in an XML
        file in this format. In other words, this should be omitted in the XML file that is sent to
        the ORCID administrators when requesting client creation or client
        updates.</xs:documentation>
    </xs:annotation>
  </xs:element>
  <xs:simpleType name="orcid">
    <xs:restriction base="xs:string">
      <xs:pattern value="(\d{4}-){3,}\d{3}[\dX]"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="email">
    <xs:restriction base="xs:string">
      <xs:pattern value="[^@]+@[^\.]+\..+"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="short-text">
    <xs:restriction base="xs:string">
      <xs:minLength value="3"/>
      <xs:maxLength value="300"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="client-type">
    <xs:restriction base="xs:string">
      <xs:enumeration value="creator"/>
      <xs:enumeration value="updater"/>
    </xs:restriction>
  </xs:simpleType>
</xs:schema>

=== ORCID/ORCID-Parent/schemas/orcid-client-group/1.0/samples/orcid-client-group-request.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
    
    =============================================================================
    Copyright (C) 2011-12 by ORCID
    
    Permission is hereby granted, free of charge, to any person obtaining a copy
    of this software and associated documentation files (the "Software"), to deal
    in the Software without restriction, including without limitation the rights
    to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
    copies of the Software, and to permit persons to whom the Software is
    furnished to do so, subject to the following conditions:
    
    The above copyright notice and this permission notice shall be included in
    all copies or substantial portions of the Software.
    
    THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
    IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
    FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
    AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
    LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
    OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
    THE SOFTWARE.
    =============================================================================
    
-->
<!-- 
    This is an example file to request creation of client details for use in
    OAuth2 authorization requests. The file will be sent from the client system
    adminstrators to the ORCID administrators (as an email attachement). 
-->
<orcid-client-group xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="http://www.orcid.org/ns/orcid ../orcid-client-group-1.0.xsd"
 xmlns="http://www.orcid.org/ns/orcid">
    <group-name>Elsevier</group-name>
    <email>orcid-admin@elsevier.com</email>
    <orcid-client>
        <display-name>Ecological Complexity</display-name>
        <website>http://www.journals.elsevier.com/ecological-complexity</website>
        <short-description>An International Journal on Biocomplexity in the Environment and Theoretical Ecology</short-description>
        <redirect-uris>
            <redirect-uri>http://www.journals.elsevier.com/ecological-complexity/orcid-callback</redirect-uri>
        </redirect-uris>
    </orcid-client>
    <orcid-client>
        <display-name>Ecological Economics</display-name>
        <website>http://www.journals.elsevier.com/ecological-economics</website>
        <short-description>The Transdisciplinary Journal of the International Society for Ecological Economics (ISEE)</short-description>
        <redirect-uris>
            <redirect-uri>http://www.journals.elsevier.com/ecological-economics/orcid-callback</redirect-uri>
        </redirect-uris>
    </orcid-client>
</orcid-client-group>
